
Table User {
  userId     Int       [pk, increment]
  username   String    @unique
  email      String    @unique
  password   String
  bio        String?
  posts      Post[]
  comments   Comment[]
  likes      Like[]
  followers  Follower[] 
  following  Follower[] 
  trips      Trip[]
}

Table Post {
  postId     Int       [pk, increment]
  userId     Int
  imageUrl   String
  caption    String?
  user       User      
  tripId     Int?
  trip       Trip?     
  comments   Comment[]
  likes      Like[]
}

Table Comment {
  commentId    Int      [pk, increment]
  postId       Int
  userId       Int
  commentText  String
  post         Post     
  user         User     
}

Table Like {
  likeId       Int      [pk, increment]
  postId       Int
  userId       Int
  post         Post     
  user         User     
}

Table Follower {
  followerId       Int     [pk, increment]
  userId           Int
  followerUserId   Int
  user             User    
  follower         User     
}

Table Trip {
  tripId       Int      [pk, increment]
  userId       Int
  tripName     String
  description  String?
  startDate    DateTime
  endDate      DateTime
  user         User     
  posts        Post[]
}

